 - 
   name: Upgrade all Flatpaks
   community.general.flatpak:
    state: latest
   register: flatpak_update_output
   debug:
    msg: "Flatpaks were{{ ' not' if not flatpak_update_output.changed else '' }} updated"


